### ISSUE TITLE
Using @gorm.AuditStamp with parent and child domian classes fail

### ISSUE THREAD

**Issue by zaccak** [yakworks/grails-audit-trail#28]
For some reason
If you have 

@gorm.AuditStamp
class A

@gorm.AuditStamp
class B extends A

This works (somtimes..)

but if you have
@gorm.AuditStamp
class A

@gorm.AuditStamp
class B extends A

@gorm.AuditStamp
class C extends A

Class C will always fail on validation with null's in the audit fields.

Workaround: Just remove the @gorm.AuditStamp on all child classes.

**Comment by zaccak** [comment]
This problem still exists in 2.1.1

I have an abstract base class with audit on and 2 subclasses of this (also with audit on). One of the subclasses works the other complains about missing audit fields. If I remove audit from both of the sub-classes but keep it on the parent base class then it works.

**Comment by basejump** [comment]
hmm, not sure how to fix it. we don't use it on base classes. A PR would be most welcome if you figure it out.

**Comment by zaccak** [comment]
I'm super swamped for the next month.. but I can try and look at it if / when I get some time in the future.

**Comment by snimavat** [comment]
Looks like the plugin should not do AST transformation of the domain class, if any of the parent domains are already transformed.
