### ISSUE TITLE
restructure project

### ISSUE THREAD

**Issue by snimavat** [yakworks/grails-audit-trail#44]

**Comment by snimavat** [comment]
@basejump We have a problem when restructuring the project.

Within our AuditStamp AST -- we do

```
private static final ConfigObject CO = new ConfigSlurper().parse(getContents(new File("grails-app/conf/application.groovy")));
Map<String, FieldProps> fprops = FieldProps.buildFieldMap(CO);
```

We do this to read the application.groovy file. This works as long as the project itself is a root level project. but when the project is nested as a sub project, it will try to find grails-app/conf/application.groovy in root project and will fail.

So far i havent been able to figureout how to get AST to look up the correct file, regard less of the location of plugin or location of the test-project.

System properties wont work either, as its compile time and base.dir isnt available.
No one had answer on slack either so far.

If you have any suggestions.

**Comment by basejump** [comment]
leave it like it was? what are the implications of not doing anything?

**Comment by snimavat** [comment]
We can keep it as it is. just works.
